<a href="https://colab.research.google.com/github/Vandan1009/python_1/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install faker

Collecting faker
  Downloading Faker-27.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-27.0.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 18.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-27.0.0

In [4]:
from faker import Faker
fake = Faker()

In [ ]:
print(fake.name())

James Ramirez

In [ ]:
print(fake.email())

kristasanders@example.com

In [ ]:
print(fake.country())

France

In [ ]:
print(fake.country())

Samoa

In [ ]:
print(fake.name())

Jeffery Reyes

In [ ]:
print(fake.text())

Indeed effort everybody memory keep animal carry. Painting wear only ball audience.
Word start personal. Door across plant especially bag dream citizen film. All education life.

In [ ]:
print(fake.latitude(), fake.longitude())

60.0310645 -40.113524

In [ ]:
print(fake.url())

https://lee.com/

In [ ]:
from random import randint
import pandas as pd
def input_data(x):

    # pandas dataframe
    data = pd.DataFrame()
    for i in range(0, x):
        data.loc[i,'product_id']= randint(1, 100)
        data.loc[i,'product_name']= fake.commerce.product_name()
        data.loc[i,'address']= fake.commerce.product_address()
        data.loc[i,'price']= randint(2000,30000)

    return data
input_data(10)

AttributeError: 'Generator' object has no attribute 'commerce'

In [ ]:
import pandas as pd
from random import randint, uniform, choice
from faker import Faker

fake = Faker()

def input_data(x):
    # List of product names for the accessories category
    accessories = ['belt', 'earring', 'glasses', 'glove', 'handbags', 'sun glasses', 'hat', 'watch', 'ring', 'necktie', 'helmet']

    # pandas dataframe
    data = pd.DataFrame()
    for i in range(0, x):
        data.loc[i, 'product_name'] = choice(accessories)
        data.loc[i, 'Price'] = round(uniform(10.0, 1000.0), 2)
        data.loc[i, 'Description'] = fake.sentence()
        data.loc[i, 'Category'] = 'accessories'
        data.loc[i, 'StockQuantity'] = randint(1, 100)
        data.loc[i, 'Brand'] = fake.company()
        data.loc[i, 'Rating'] = round(uniform(1.0, 5.0), 1)
        data.loc[i, 'Warehouse'] = fake.city()
    return data

# Example usage
input_data(10)

,product_name,Price,Description,Category,StockQuantity,Brand,Rating,Warehouse
0,glasses,782.44,Physical message as personal.,accessories,57.0,Miles-White,4.6,North Megan
1,ring,888.85,Remain represent character.,accessories,88.0,Rodriguez Inc,4.4,North Amy
2,earring,470.35,Program door TV resource no speak.,accessories,86.0,"Fletcher, Hamilton and Cox",1.2,South Jamestown
3,belt,244.07,Scene arm learn knowledge old sort.,accessories,67.0,Hill-Roberson,1.4,East Brittney
4,sun glasses,916.38,Mission make when opportunity.,accessories,42.0,Patrick Inc,3.6,Oscarport
5,earring,751.32,Receive born decision up.,accessories,18.0,Gomez-Stewart,2.8,Rebeccaburgh
6,belt,455.37,Service participant who center no late key com...,accessories,55.0,Weber-Carter,4.5,Victoriaport
7,watch,793.25,Window exactly different very friend own.,accessories,7.0,Brennan Ltd,3.1,New Heatherton
8,glove,878.06,Sort thing adult rule include able they.,accessories,48.0,"Jackson, Atkins and Watson",3.3,West Paul
9,glove,287.24,Player choice enter.,accessories,78.0,Kim and Sons,1.2,Andreaburgh

In [12]:
import pandas as pd
from random import randint, uniform, choice
from faker import Faker

fake = Faker()

def input_data(x):
    # List of product names for the accessories category
    accessories = ['Belt','Earring','Glasses','Glove','Handbag','Hat','Helmet','Necktie','Perfume','Ring','Sash','Sunglasses','Umbrella','Watch','Anklets','Bangles and Bracelets','Brooches and Pins','Cuff Links and Studs','Hair Accessories','Handkerchiefs and Pocket Squares','Luggage','Necklaces and Pendants','Wallets']

    # List of brand names for the accessories category
    brands = ['Gucci','Fossil', 'Prada','Kate Spade','Tory Burch','Bvlgari','Cartier','Swarovski','Ray-Ban','Oakley', 'Louis Vuitton', 'Chanel','Michael Kors','Coach', 'Hermes', 'Fendi', 'Balenciaga', 'Dior', 'Versace', 'Burberry']

    # pandas dataframe
    data = pd.DataFrame()
    for i in range(0, x):
        data.loc[i, 'product_name'] = choice(accessories)
        data.loc[i, 'Price'] = round(uniform(100.0, 10000.0), 2)
        data.loc[i, 'Description'] = fake.sentence()
        data.loc[i, 'Category'] = 'accessories'
        data.loc[i, 'StockQuantity'] = randint(1, 100)
        data.loc[i, 'Brand'] = choice(brands)
        data.loc[i, 'Rating'] = round(uniform(1.0, 5.0), 1)
        data.loc[i, 'Warehouse'] = fake.city()
    return data

# Example usage
input_data(10)

,product_name,Price,Description,Category,StockQuantity,Brand,Rating,Warehouse
0,Hat,8196.20,Well of I level and size that professor.,accessories,99.0,Ray-Ban,3.4,Port Amandafurt
1,Perfume,6622.09,Class PM exactly.,accessories,38.0,Versace,4.3,South Williammouth
2,Bangles and Bracelets,316.40,Cut a structure father.,accessories,7.0,Versace,3.4,New Donborough
3,Earring,3764.93,Sense others service notice once.,accessories,23.0,Burberry,1.3,South Kevin
4,Handkerchiefs and Pocket Squares,7380.65,Window they even think huge.,accessories,61.0,Tory Burch,1.6,North Matthewfurt
5,Umbrella,4307.06,Necessary drug catch event paper summer wall.,accessories,68.0,Louis Vuitton,3.4,Fernandezmouth
6,Handkerchiefs and Pocket Squares,8738.69,Officer ago huge indeed management fill really.,accessories,72.0,Michael Kors,1.3,East Michael
7,Helmet,5123.89,Tend subject teach reason enough dog by doctor.,accessories,26.0,Versace,2.3,Christinestad
8,Handkerchiefs and Pocket Squares,9697.82,Wall four both society author detail.,accessories,79.0,Bvlgari,4.3,New Aaron
9,Hair Accessories,3676.11,Upon prove real movie land.,accessories,42.0,Chanel,2.7,South Jeffreyton

In [9]:
import pandas as pd
from random import randint, uniform, choice
from faker import Faker

fake = Faker()

# List of book categories
book_categories = [
    "Fantasy", "Science Fiction", "Mystery", "Horror", "Historical Fiction", "Women’s Fiction",
    "Literary Fiction", "Magic Realism", "Graphic Novel", "Short Story", "Young Adult", "New Adult",
    "Dystopian", "Action & Adventure", "Thriller & Suspense", "Romance", "Children’s", "Contemporary Fiction",
    "Biography", "Self-Help", "History", "Memoir & Autobiography", "Food & Drink", "Art & Photography", "Travel"
]

def input_data(x):
    # pandas dataframe
    data = pd.DataFrame()
    for i in range(0, x):
        data.loc[i, 'product_name'] = choice(book_categories)
        data.loc[i, 'Price'] = round(uniform(100.0, 4000.0), 2)
        data.loc[i, 'Description'] = fake.sentence()
        data.loc[i, 'Category'] = 'Books'
        data.loc[i, 'StockQuantity'] = randint(1, 100)
        data.loc[i, 'Brand'] = fake.company()
        data.loc[i, 'Rating'] = round(uniform(1.0, 5.0), 1)
        data.loc[i, 'Warehouse'] = fake.city()
        print(data.info())
    return data

# Example usage
input_data(10)

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   1 non-null      object
 1   Price          1 non-null      float64
 2   Description    1 non-null      object
 3   Category       1 non-null      object
 4   StockQuantity  1 non-null      float64
 5   Brand          1 non-null      object
 6   Rating         1 non-null      float64
 7   Warehouse      1 non-null      object
dtypes: float64(3), object(5)
memory usage: 180.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   2 non-null      object
 1   Price          2 non-null      float64
 2   Description    2 non-null      object
 3   Category       2 non-null      object
 4   StockQuantity  2 non-null      float64
 5   Brand          2 non-null      object
 6   Rating         2 non-null      float64
 7   Warehouse      2 non-null      object
dtypes: float64(3), object(5)
memory usage: 252.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   3 non-null      object
 1   Price          3 non-null      float64
 2   Description    3 non-null      object
 3   Category       3 non-null      object
 4   StockQuantity  3 non-null      float64
 5   Brand          3 non-null      object
 6   Rating         3 non-null      float64
 7   Warehouse      3 non-null      object
dtypes: float64(3), object(5)
memory usage: 324.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   4 non-null      object
 1   Price          4 non-null      float64
 2   Description    4 non-null      object
 3   Category       4 non-null      object
 4   StockQuantity  4 non-null      float64
 5   Brand          4 non-null      object
 6   Rating         4 non-null      float64
 7   Warehouse      4 non-null      object
dtypes: float64(3), object(5)
memory usage: 460.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   5 non-null      object
 1   Price          5 non-null      float64
 2   Description    5 non-null      object
 3   Category       5 non-null      object
 4   StockQuantity  5 non-null      float64
 5   Brand          5 non-null      object
 6   Rating         5 non-null      float64
 7   Warehouse      5 non-null      object
dtypes: float64(3), object(5)
memory usage: 532.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   6 non-null      object
 1   Price          6 non-null      float64
 2   Description    6 non-null      object
 3   Category       6 non-null      object
 4   StockQuantity  6 non-null      float64
 5   Brand          6 non-null      object
 6   Rating         6 non-null      float64
 7   Warehouse      6 non-null      object
dtypes: float64(3), object(5)
memory usage: 604.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   7 non-null      object
 1   Price          7 non-null      float64
 2   Description    7 non-null      object
 3   Category       7 non-null      object
 4   StockQuantity  7 non-null      float64
 5   Brand          7 non-null      object
 6   Rating         7 non-null      float64
 7   Warehouse      7 non-null      object
dtypes: float64(3), object(5)
memory usage: 804.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   8 non-null      object
 1   Price          8 non-null      float64
 2   Description    8 non-null      object
 3   Category       8 non-null      object
 4   StockQuantity  8 non-null      float64
 5   Brand          8 non-null      object
 6   Rating         8 non-null      float64
 7   Warehouse      8 non-null      object
dtypes: float64(3), object(5)
memory usage: 876.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   9 non-null      object
 1   Price          9 non-null      float64
 2   Description    9 non-null      object
 3   Category       9 non-null      object
 4   StockQuantity  9 non-null      float64
 5   Brand          9 non-null      object
 6   Rating         9 non-null      float64
 7   Warehouse      9 non-null      object
dtypes: float64(3), object(5)
memory usage: 948.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_name   10 non-null     object
 1   Price          10 non-null     float64
 2   Description    10 non-null     object
 3   Category       10 non-null     object
 4   StockQuantity  10 non-null     float64
 5   Brand          10 non-null     object
 6   Rating         10 non-null     float64
 7   Warehouse      10 non-null     object
dtypes: float64(3), object(5)
memory usage: 1020.0+ bytes
None

,product_name,Price,Description,Category,StockQuantity,Brand,Rating,Warehouse
0,Travel,3489.63,Small those try value.,Books,69.0,"Drake, May and Gibson",3.1,Port Henry
1,Young Adult,3231.98,Likely under yet sing.,Books,40.0,Brown Inc,3.9,East Christineburgh
2,Thriller & Suspense,1052.90,Along poor agreement describe.,Books,95.0,Chan Ltd,2.6,North Melanie
3,Memoir & Autobiography,2428.19,Subject must director far age message.,Books,45.0,"Wilson, Wilson and Wheeler",4.7,West Kathleenland
4,Fantasy,3692.51,Successful moment oil action create.,Books,34.0,Graham-Hill,2.4,Scottstad
5,Self-Help,1701.62,Control country president.,Books,87.0,Huerta PLC,1.8,Cynthiaport
6,Graphic Novel,2067.81,Beat fall pressure radio sister check discover...,Books,63.0,Ball-Kline,3.2,East Jayhaven
7,Science Fiction,3948.83,Than pass each under.,Books,34.0,Swanson-Soto,2.2,Kristenstad
8,Food & Drink,487.00,Choose measure drive pretty.,Books,35.0,Brown-Gentry,3.7,North Raven
9,Literary Fiction,2924.62,News common exactly final fine parent positive.,Books,84.0,"Berg, Ramirez and Jones",1.2,Port Katie

In [13]:
import pandas as pd
from random import randint, uniform, choice
from faker import Faker

fake = Faker()

# List of book categories
book_categories = [
    "Fantasy", "Science Fiction", "Mystery", "Horror", "Historical Fiction", "Women’s Fiction",
    "Literary Fiction", "Magic Realism", "Graphic Novel", "Short Story", "Young Adult", "New Adult",
    "Dystopian", "Action & Adventure", "Thriller & Suspense", "Romance", "Children’s", "Contemporary Fiction",
    "Biography", "Self-Help", "History", "Memoir & Autobiography", "Food & Drink", "Art & Photography", "Travel"
]

def input_data(x):
    # pandas dataframe
    data = pd.DataFrame()
    for i in range(0, x):
        data.loc[i, 'product_name'] = choice(book_categories)
        data.loc[i, 'Price'] = round(uniform(10.0, 1000.0), 2)
        data.loc[i, 'Description'] = fake.sentence()
        data.loc[i, 'Category'] = 'Books'
        data.loc[i, 'Author'] = fake.name()
        data.loc[i, 'StockQuantity'] = randint(1, 100)
        data.loc[i, 'Brand'] = fake.company()
        data.loc[i, 'Rating'] = round(uniform(1.0, 5.0), 1)
        data.loc[i, 'Warehouse'] = fake.city()
    return data

# Example usage
input_data(10)

,product_name,Price,Description,Category,Author,StockQuantity,Brand,Rating,Warehouse
0,Contemporary Fiction,36.35,Though thousand again within.,Books,David Lee,14.0,Shepherd-Martinez,3.8,West Michaelbury
1,Biography,848.28,Result drive until cost dinner state.,Books,Michael Li,42.0,Martinez-Valencia,1.2,Gilbertton
2,Magic Realism,795.58,Plan level same partner.,Books,Christina Wilson,88.0,"Thompson, Robinson and Miller",3.6,Justinchester
3,Mystery,425.18,Room throughout order you continue.,Books,Jesse Simmons,56.0,Hawkins-Turner,1.4,Lake Sheriton
4,Self-Help,344.44,Improve front theory film.,Books,Jennifer Johnson,76.0,Booker-Hudson,3.9,Port Debra
5,New Adult,457.69,Option may fish writer it.,Books,Angela Morrison,73.0,"Lewis, Stewart and Brady",4.9,West Larryview
6,Fantasy,227.58,Race hundred until foot five.,Books,Joshua Frye,65.0,"Oconnell, Gonzales and Barrett",2.9,West Teresa
7,Historical Fiction,620.39,Mean when TV only.,Books,James Garcia,80.0,"Brooks, Olson and Dominguez",4.5,Darrellview
8,Memoir & Autobiography,688.53,Teacher plant record hotel step simple address.,Books,Victoria Yates,77.0,"Price, Miller and Deleon",3.8,Sheaview
9,History,580.14,Various expert customer popular.,Books,Stephanie Costa,2.0,"Nelson, Singh and Hebert",1.4,East Donna